include:
  - board: nice_nano@2.0.0
    shield: settings_reset
  - board: nice_nano@2.0.0
    shield: sofle_dongle
  - board: nice_nano@2.0.0
    shield: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano@2.0.0
    shield: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
