# Bluetooth name
CONFIG_ZMK_KEYBOARD_NAME="Sofle Dongle"

# Central peripheral count
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# Enable USB Logging
CONFIG_ZMK_USB_LOGGING=y

# Disable external power management
CONFIG_ZMK_EXT_POWER=n

# Enable OLED Display
# CONFIG_ZMK_DISPLAY=y

# Enable RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
