# Bluetooth name
CONFIG_ZMK_KEYBOARD_NAME="Sofle Dongle"

# Better Bluetooth compatibility
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable OLED Display
# CONFIG_ZMK_DISPLAY=y

# Enable RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
